---
env:
  global:
    - WORKSPACE="/ci-actions/workspace"
    - REMARKLINT_VERSION="6.0.4"

stages:
  - markdown-lint
  - elixir-lint
  - test-1.3
  - test-1.4
  - test-1.5
  - test-1.6
  - test-1.7
  - test-1.8

jobs:
  include:
    - stage: markdown-lint
      language: bash
      image: docker:18-git
      before_script:
        - docker pull smoloney/ci-actions-remark:${REMARKLINT_VERSION} > /dev/null
      script:
        - |
          docker run --rm -v ${PWD}:${WORKSPACE} smoloney/ci-actions-remark:${REMARKLINT_VERSION} \
          --exclude='./deps' \
          --exclude='./_build' \
          --exec-args='--frail --rc-path ./.remarkrc'

    - stage: markdown-lint
      language: elixir
      elixir: 1.8
      otp_release: 21.2
      script:
        - mix format --check-formatted --dry-run

    - &test
      stage: test-1.3
      language: elixir
      elixir: 1.3
      otp_release: 19.2
      script:
        - mix test

    - <<: *test
      stage: test-1.4
      elixir: 1.4
      otp_release: 19.2

    - <<: *test
      stage: test-1.5
      elixir: 1.5
      otp_release: 20.3

    - <<: *test
      stage: test-1.6
      elixir: 1.6
      otp_release: 20.3

    - <<: *test
      stage: test-1.7
      elixir: 1.7
      otp_release: 20.3

    - <<: *test
      stage: test-1.8
      elixir: 1.8
      otp_release: 21.2
